LogicalID:
  Type: "AWS::EC2::Subnet"
  Properties:
    AssignIpv6AddressOnCreation: Boolean
    AvailabilityZone: String
    CidrBlock: String #required
    Ipv6CidrBlock: String
    MapPublicIpOnLaunch: Boolean
    Tags:
      - Tag
    VpcId: String #required
